import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import { ThemeProvider } from "@/components/theme-provider";
import SidebarNav from "@/components/SidebarNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Winter Ticketing App",
  description: "Generated by Islandtechies",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col bg-slate-50`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex w-full">
            <div className="w-[25rem] h-screen">
              <SidebarNav />
            </div>
            <div className="w-full p-10 md:p-16 bg-slate-100 max-h-screen overflow-y-scroll">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
